- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - git
      - python3-colcon-common-extensions
      - python3-colcon-mixin
      - python3-flake8
      - python3-pip
      - python3-pytest-cov
      - python3-rosdep
      - python3-setuptools
      - python3-vcstool
      - wget
    state: latest
    update_cache: true

- name: Install pip packages
  ansible.builtin.pip:
    name:
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
      - setuptools
    state: latest
    executable: pip3

- name: Run 'sudo rosdep init'
  become: true
  ansible.builtin.command:
    cmd: rosdep init
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
