name: free-disk-space
description: ""

runs:
  using: composite
  steps:
    - name: Install sudo
      run: |
        if ! (command -v sudo >/dev/null 2>&1); then
            apt-get -y update
            apt-get -y install sudo
        fi
      shell: bash

    # https://github.community/t/bug-strange-no-space-left-on-device-ioexceptions-on-github-runners/17616
    - name: Free disk space
      run: |
        df -h

        sudo apt-get -y purge \
          dotnet* \
          ghc* \
          php* \
          || true
        sudo apt-get -y autoremove
        sudo apt-get -y autoclean

        sudo rm -rf \
          /usr/local/lib/android \
          /usr/share/dotnet/ \
          /opt/ghc

        docker rmi $(docker image ls -aq) || true

        df -h
      shell: bash
