name: build-main-self-hosted

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  build-main-self-hosted:
    needs: load-env
    runs-on: [self-hosted, linux, ARM64]
    container: ${{ needs.load-env.outputs.base-image }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos

      - name: Run vcs export
        run: |
          vcs export --exact src || true

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro ${{ needs.load-env.outputs.rosdistro }}

      - name: Build
        run: |
          . /opt/ros/${{ needs.load-env.outputs.rosdistro }}/setup.sh
          colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release
